spring:
  profiles:
    include:
      core
      api-common
      domain

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
---
spring:
  config.activate.on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: embedded
      platform: h2

---
spring:
  config.activate.on-profile: dev
